export const ADD_NODE = "ADD_NODE";
export const ADD_NODE_SUCCESS = "ADD_NODE_SUCCESS"
export const ADD_NODE_ERROR = "ADD_NODE_ERROR"

export const GET_NODES = "GET_NODES";
export const GET_NODES_SUCCESS = "GET_NODES_SUCCESS"
export const GET_NODES_ERROR = "GET_NODES_ERROR"

export const GET_NODES_DEPENDENCIES_SUCCESS = "GET_NODES_DEPENDENCIES_SUCCESS"

export const SELECT_NODE = "SELECT_NODE";

export const ADD_NODE_DEPENDENCY = "ADD_NODE_DEPENDENCY";
export const ADD_NODE_DEPENDENCY_SUCCESS = "ADD_NODE_DEPENDENCY_SUCCESS";
export const ADD_NODE_DEPENDENCY_ERROR = "ADD_NODE_DEPENDENCY_ERROR";

export const REMOVE_NODE_DEPENDENCY = "REMOVE_NODE_DEPENDENCY";
export const REMOVE_NODE_DEPENDENCY_SUCCESS = "REMOVE_NODE_DEPENDENCY_SUCCESS";
export const REMOVE_NODE_DEPENDENCY_ERROR = "REMOVE_NODE_DEPENDENCY_ERROR";

export const UPDATE_NODE_HEALTH = "UPDATE_NODE_HEALTH";

